// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KNSMZ_Save","status":true,"description":"ver.1.0.2 Add screenshots on Save/Load scene.","parameters":{"MaxSaveFile":"25","InfoHorzLineColor":"gray","Vocab":"","VocabPrice":"Money","VocabPlace":"Location","Screenshot":"","ImageSize":"{\"width\":\"280\",\"height\":\"220\"}","ImagePivot":"{\"x\":\"408\",\"y\":\"224\"}","RadiusSize":"{\"width\":\"560\",\"height\":\"80\"}","ImageBorderColor":"black","ArrowImage":"KnsSave_HUD","ImageExists":"KnsSave_HasData","NoImageExists":"KnsSave_NoData","UseScreenshot":"true","WhenUseImage":"","ImageSaveSize":"{\"width\":\"128\",\"height\":\"96\"}","ImageType":"jpeg","JpegQuality":"50","SetMonochrome":"false","Windows":"","HelpWindow":"{\"point\":\"{\\\"x\\\":\\\"0\\\",\\\"y\\\":\\\"0\\\"}\",\"surface\":\"{\\\"width\\\":\\\"660\\\",\\\"height\\\":\\\"72\\\"}\",\"windowType\":\"0\"}","InfoWindow":"{\"point\":\"{\\\"x\\\":\\\"0\\\",\\\"y\\\":\\\"432\\\"}\",\"surface\":\"{\\\"width\\\":\\\"816\\\",\\\"height\\\":\\\"192\\\"}\",\"windowType\":\"0\"}"}}
];
