// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"Custom","status":true,"description":"Test Plugin","parameters":{}}
];
