#!/bin/bash

# copy this file to location `.git/hooks/pre-commit`
# or use **admin cmd** to run `mklink .\.git\hooks\pre-commit [Absolute path of current project]\.githooks\pre-commit`

echo "Executing pre-commit hook... (Make sure that you are at root of the project)"
node ./.githooks/json_formatter.mjs unminify data
git add -A
